export const countries = [
  { code: "AD", label: "Andorra", phone: "376", phoneLength: 6, flag: "🇦🇩" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
    phoneLength: 9,
    flag: "🇦🇪",
  },
  { code: "AF", label: "Afghanistan", phone: "93", phoneLength: 9, flag: "🇦🇫" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
    phoneLength: 10,
    flag: "🇦🇬",
  },
  {
    code: "AI",
    label: "Anguilla",
    phone: "1-264",
    phoneLength: 10,
    flag: "🇦🇮",
  },
  { code: "AL", label: "Albania", phone: "355", phoneLength: 9, flag: "🇦🇱" },
  { code: "AM", label: "Armenia", phone: "374", phoneLength: 6, flag: "🇦🇲" },
  { code: "AO", label: "Angola", phone: "244", phoneLength: 9, flag: "🇦🇴" },
  { code: "AQ", label: "Antarctica", phone: "672", phoneLength: 6, flag: "🇦🇶" },
  {
    code: "AR",
    label: "Argentina",
    phone: "54",
    phoneLength: [6, 7, 8],
    flag: "🇦🇷",
  },
  {
    code: "AS",
    label: "American Samoa",
    phone: "1-684",
    phoneLength: 10,
    flag: "🇦🇸",
  },
  {
    code: "AT",
    label: "Austria",
    phone: "43",
    phoneLength: [10, 11],
    flag: "🇦🇹",
  },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
    phoneLength: 9,
    flag: "🇦🇺",
  },
  { code: "AW", label: "Aruba", phone: "297", phoneLength: 7, flag: "🇦🇼" },
  {
    code: "AX",
    label: "Alland Islands",
    phone: "358",
    phoneLength: [7, 10],
    flag: "🇦🇽",
  },
  { code: "AZ", label: "Azerbaijan", phone: "994", phoneLength: 9, flag: "🇦🇿" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
    phoneLength: 8,
    flag: "🇧🇦",
  },
  {
    code: "BB",
    label: "Barbados",
    phone: "1-246",
    phoneLength: 10,
    flag: "🇧🇧",
  },
  {
    code: "BD",
    label: "Bangladesh",
    phone: "880",
    phoneLength: 10,
    flag: "🇧🇩",
  },
  { code: "BE", label: "Belgium", phone: "32", phoneLength: 9, flag: "🇧🇪" },
  {
    code: "BF",
    label: "Burkina Faso",
    phone: "226",
    phoneLength: 8,
    flag: "🇧🇫",
  },
  { code: "BG", label: "Bulgaria", phone: "359", phoneLength: 9, flag: "🇧🇬" },
  { code: "BH", label: "Bahrain", phone: "973", phoneLength: 8, flag: "🇧🇭" },
  { code: "BI", label: "Burundi", phone: "257", phoneLength: 8, flag: "🇧🇮" },
  { code: "BJ", label: "Benin", phone: "229", phoneLength: 8, flag: "🇧🇯" },
  {
    code: "BL",
    label: "Saint Barthelemy",
    phone: "590",
    phoneLength: 9,
    flag: "🇧🇱",
  },
  { code: "BM", label: "Bermuda", phone: "1-441", phoneLength: 10, flag: "🇧🇲" },
  {
    code: "BN",
    label: "Brunei Darussalam",
    phone: "673",
    phoneLength: 7,
    flag: "🇧🇳",
  },
  { code: "BO", label: "Bolivia", phone: "591", phoneLength: 9, flag: "🇧🇴" },
  { code: "BR", label: "Brazil", phone: "55", phoneLength: 11, flag: "🇧🇷" },
  { code: "BS", label: "Bahamas", phone: "1-242", phoneLength: 10, flag: "🇧🇸" },
  { code: "BT", label: "Bhutan", phone: "975", phoneLength: 7, flag: "🇧🇹" },
  {
    code: "BV",
    label: "Bouvet Island",
    phone: "47",
    phoneLength: 10,
    flag: "🇧🇻",
  },
  { code: "BW", label: "Botswana", phone: "267", phoneLength: 7, flag: "🇧🇼" },
  { code: "BY", label: "Belarus", phone: "375", phoneLength: 9, flag: "🇧🇾" },
  { code: "BZ", label: "Belize", phone: "501", phoneLength: 7, flag: "🇧🇿" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
    phoneLength: 10,
    flag: "🇨🇦",
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
    phoneLength: 10,
    flag: "🇨🇨",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
    phoneLength: 7,
    flag: "🇨🇩",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
    phoneLength: 8,
    flag: "🇨🇫",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "242",
    phoneLength: 9,
    flag: "🇨🇬",
  },
  { code: "CH", label: "Switzerland", phone: "41", phoneLength: 9, flag: "🇨🇭" },
  {
    code: "CI",
    label: "Cote d'Ivoire",
    phone: "225",
    phoneLength: 8,
    flag: "🇨🇮",
  },
  {
    code: "CK",
    label: "Cook Islands",
    phone: "682",
    phoneLength: 5,
    flag: "🇨🇰",
  },
  { code: "CL", label: "Chile", phone: "56", phoneLength: 9, flag: "🇨🇱" },
  { code: "CM", label: "Cameroon", phone: "237", phoneLength: 9, flag: "🇨🇲" },
  { code: "CN", label: "China", phone: "86", phoneLength: 11, flag: "🇨🇳" },
  { code: "CO", label: "Colombia", phone: "57", phoneLength: 10, flag: "🇨🇴" },
  { code: "CR", label: "Costa Rica", phone: "506", phoneLength: 8, flag: "🇨🇷" },
  { code: "CU", label: "Cuba", phone: "53", phoneLength: 8, flag: "🇨🇺" },
  { code: "CV", label: "Cape Verde", phone: "238", phoneLength: 7, flag: "🇨🇻" },
  { code: "CW", label: "Curacao", phone: "599", phoneLength: 7, flag: "🇨🇼" },
  {
    code: "CX",
    label: "Christmas Island",
    phone: "61",
    phoneLength: 9,
    flag: "🇨🇽",
  },
  { code: "CY", label: "Cyprus", phone: "357", phoneLength: 8, flag: "🇨🇾" },
  {
    code: "CZ",
    label: "Czech Republic",
    phone: "420",
    phoneLength: 9,
    flag: "🇨🇿",
  },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
    phoneLength: 10,
    flag: "🇩🇪",
  },
  { code: "DJ", label: "Djibouti", phone: "253", phoneLength: 10, flag: "🇩🇯" },
  { code: "DK", label: "Denmark", phone: "45", phoneLength: 8, flag: "🇩🇰" },
  {
    code: "DM",
    label: "Dominica",
    phone: "1-767",
    phoneLength: 10,
    flag: "🇩🇲",
  },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
    phoneLength: 10,
    flag: "🇩🇴",
  },
  { code: "DZ", label: "Algeria", phone: "213", phoneLength: 9, flag: "🇩🇿" },
  { code: "EC", label: "Ecuador", phone: "593", phoneLength: 9, flag: "🇪🇨" },
  { code: "EE", label: "Estonia", phone: "372", phoneLength: 8, flag: "🇪🇪" },
  { code: "EG", label: "Egypt", phone: "20", phoneLength: 10, flag: "🇪🇬" },
  {
    code: "EH",
    label: "Western Sahara",
    phone: "212",
    phoneLength: 9,
    flag: "🇪🇭",
  },
  { code: "ER", label: "Eritrea", phone: "291", phoneLength: 7, flag: "🇪🇷" },
  { code: "ES", label: "Spain", phone: "34", phoneLength: 9, flag: "🇪🇸" },
  { code: "ET", label: "Ethiopia", phone: "251", phoneLength: 9, flag: "🇪🇹" },
  {
    code: "FI",
    label: "Finland",
    phone: "358",
    phoneLength: [9, 11],
    flag: "🇫🇮",
  },
  { code: "FJ", label: "Fiji", phone: "679", phoneLength: 7, flag: "🇫🇯" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
    phoneLength: 5,
    flag: "🇫🇰",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
    phoneLength: 7,
    flag: "🇫🇲",
  },
  {
    code: "FO",
    label: "Faroe Islands",
    phone: "298",
    phoneLength: 5,
    flag: "🇫🇴",
  },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
    phoneLength: 9,
    flag: "🇫🇷",
  },
  { code: "GA", label: "Gabon", phone: "241", phoneLength: 7, flag: "🇬🇦" },
  {
    code: "GB",
    label: "United Kingdom",
    phone: "44",
    phoneLength: 10,
    flag: "🇬🇧",
  },
  { code: "GD", label: "Grenada", phone: "1-473", phoneLength: 10, flag: "🇬🇩" },
  { code: "GE", label: "Georgia", phone: "995", phoneLength: 9, flag: "🇬🇪" },
  {
    code: "GF",
    label: "French Guiana",
    phone: "594",
    phoneLength: 9,
    flag: "🇬🇫",
  },
  { code: "GG", label: "Guernsey", phone: "44", phoneLength: 10, flag: "🇬🇬" },
  { code: "GH", label: "Ghana", phone: "233", phoneLength: 9, flag: "🇬🇭" },
  { code: "GI", label: "Gibraltar", phone: "350", phoneLength: 8, flag: "🇬🇮" },
  { code: "GL", label: "Greenland", phone: "299", phoneLength: 6, flag: "🇬🇱" },
  { code: "GM", label: "Gambia", phone: "220", phoneLength: 7, flag: "🇬🇲" },
  { code: "GN", label: "Guinea", phone: "224", phoneLength: 9, flag: "🇬🇳" },
  { code: "GP", label: "Guadeloupe", phone: "590", phoneLength: 9, flag: "🇬🇵" },
  {
    code: "GQ",
    label: "Equatorial Guinea",
    phone: "240",
    phoneLength: 9,
    flag: "🇬🇶",
  },
  { code: "GR", label: "Greece", phone: "30", phoneLength: 10, flag: "🇬🇷" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
    phoneLength: 5,
    flag: "🇬🇸",
  },
  { code: "GT", label: "Guatemala", phone: "502", phoneLength: 8, flag: "🇬🇹" },
  { code: "GU", label: "Guam", phone: "1-671", phoneLength: 10, flag: "🇬🇺" },
  {
    code: "GW",
    label: "Guinea-Bissau",
    phone: "245",
    phoneLength: 9,
    flag: "🇬🇼",
  },
  { code: "GY", label: "Guyana", phone: "592", phoneLength: 7, flag: "🇬🇾" },
  { code: "HK", label: "Hong Kong", phone: "852", phoneLength: 8, flag: "🇭🇰" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
    phoneLength: 10,
    flag: "🇭🇲",
  },
  { code: "HN", label: "Honduras", phone: "504", phoneLength: 8, flag: "🇭🇳" },
  { code: "HR", label: "Croatia", phone: "385", phoneLength: 9, flag: "🇭🇷" },
  { code: "HT", label: "Haiti", phone: "509", phoneLength: 8, flag: "🇭🇹" },
  { code: "HU", label: "Hungary", phone: "36", phoneLength: 9, flag: "🇭🇺" },
  { code: "ID", label: "Indonesia", phone: "62", phoneLength: 11, flag: "🇮🇩" },
  { code: "IE", label: "Ireland", phone: "353", phoneLength: 9, flag: "🇮🇪" },
  { code: "IL", label: "Israel", phone: "972", phoneLength: 9, flag: "🇮🇱" },
  {
    code: "IM",
    label: "Isle of Man",
    phone: "44",
    phoneLength: 10,
    flag: "🇮🇲",
  },
  { code: "IN", label: "India", phone: "91", phoneLength: 10, flag: "🇮🇳" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
    phoneLength: 7,
    flag: "🇮🇴",
  },
  { code: "IQ", label: "Iraq", phone: "964", phoneLength: 10, flag: "🇮🇶" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
    phoneLength: 11,
    flag: "🇮🇷",
  },
  { code: "IS", label: "Iceland", phone: "354", phoneLength: 7, flag: "🇮🇸" },
  { code: "IT", label: "Italy", phone: "39", phoneLength: 10, flag: "🇮🇹" },
  { code: "JE", label: "Jersey", phone: "44", phoneLength: 10, flag: "🇯🇪" },
  { code: "JM", label: "Jamaica", phone: "1-876", phoneLength: 10, flag: "🇯🇲" },
  {
    code: "JO",
    label: "Jordan",
    phone: "962",
    phoneLength: [8, 9],
    flag: "🇯🇴",
  },
  { code: "JP", label: "Japan", phone: "81", suggested: true, flag: "🇯🇵" },
  { code: "KE", label: "Kenya", phone: "254", phoneLength: 10, flag: "🇰🇪" },
  { code: "KG", label: "Kyrgyzstan", phone: "996", phoneLength: 9, flag: "🇰🇬" },
  { code: "KH", label: "Cambodia", phone: "855", phoneLength: 9, flag: "🇰🇭" },
  { code: "KI", label: "Kiribati", phone: "686", phoneLength: 8, flag: "🇰🇮" },
  { code: "KM", label: "Comoros", phone: "269", phoneLength: 7, flag: "🇰🇲" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
    phoneLength: 10,
    flag: "🇰🇳",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
    phoneLength: [4, 6, 7, 13],
    flag: "🇰🇵",
  },
  {
    code: "KR",
    label: "Korea, Republic of",
    phone: "82",
    phoneLength: [7, 8],
    flag: "🇰🇷",
  },
  { code: "KW", label: "Kuwait", phone: "965", phoneLength: 8, flag: "🇰🇼" },
  {
    code: "KY",
    label: "Cayman Islands",
    phone: "1-345",
    phoneLength: 7,
    flag: "🇰🇾",
  },
  { code: "KZ", label: "Kazakhstan", phone: "7", phoneLength: 10, flag: "🇰🇿" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
    phoneLength: [8, 9],
    flag: "🇱🇦",
  },
  {
    code: "LB",
    label: "Lebanon",
    phone: "961",
    phoneLength: [7, 8],
    flag: "🇱🇧",
  },
  {
    code: "LC",
    label: "Saint Lucia",
    phone: "1-758",
    phoneLength: 7,
    flag: "🇱🇨",
  },
  {
    code: "LI",
    label: "Liechtenstein",
    phone: "423",
    phoneLength: 7,
    flag: "🇱🇮",
  },
  { code: "LK", label: "Sri Lanka", phone: "94", phoneLength: 7, flag: "🇱🇰" },
  {
    code: "LR",
    label: "Liberia",
    phone: "231",
    phoneLength: [8, 9],
    flag: "🇱🇷",
  },
  { code: "LS", label: "Lesotho", phone: "266", phoneLength: 8, flag: "🇱🇸" },
  { code: "LT", label: "Lithuania", phone: "370", phoneLength: 8, flag: "🇱🇹" },
  { code: "LU", label: "Luxembourg", phone: "352", phoneLength: 9, flag: "🇱🇺" },
  { code: "LV", label: "Latvia", phone: "371", phoneLength: 8, flag: "🇱🇻" },
  { code: "LY", label: "Libya", phone: "218", phoneLength: 10, flag: "🇱🇾" },
  { code: "MA", label: "Morocco", phone: "212", phoneLength: 9, flag: "🇲🇦" },
  { code: "MC", label: "Monaco", phone: "377", phoneLength: 8, flag: "🇲🇨" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "373",
    phoneLength: 8,
    flag: "🇲🇩",
  },
  { code: "ME", label: "Montenegro", phone: "382", phoneLength: 8, flag: "🇲🇪" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
    phoneLength: 6,
    flag: "🇲🇫",
  },
  { code: "MG", label: "Madagascar", phone: "261", phoneLength: 7, flag: "🇲🇬" },
  {
    code: "MH",
    label: "Marshall Islands",
    phone: "692",
    phoneLength: 7,
    flag: "🇲🇭",
  },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
    phoneLength: 8,
    flag: "🇲🇰",
  },
  { code: "ML", label: "Mali", phone: "223", phoneLength: 8, flag: "🇲🇱" },
  {
    code: "MM",
    label: "Myanmar",
    phone: "95",
    phoneLength: [7, 10],
    flag: "🇲🇲",
  },
  { code: "MN", label: "Mongolia", phone: "976", phoneLength: 8, flag: "🇲🇳" },
  { code: "MO", label: "Macao", phone: "853", phoneLength: 8, flag: "🇲🇴" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
    phoneLength: 7,
    flag: "🇲🇵",
  },
  { code: "MQ", label: "Martinique", phone: "596", phoneLength: 9, flag: "🇲🇶" },
  { code: "MR", label: "Mauritania", phone: "222", phoneLength: 8, flag: "🇲🇷" },
  {
    code: "MS",
    label: "Montserrat",
    phone: "1-664",
    phoneLength: 10,
    flag: "🇲🇸",
  },
  { code: "MT", label: "Malta", phone: "356", phoneLength: 8, flag: "🇲🇹" },
  { code: "MU", label: "Mauritius", phone: "230", phoneLength: 8, flag: "🇲🇺" },
  { code: "MV", label: "Maldives", phone: "960", phoneLength: 7, flag: "🇲🇻" },
  {
    code: "MW",
    label: "Malawi",
    phone: "265",
    phoneLength: [7, 8, 9],
    flag: "🇲🇼",
  },
  { code: "MX", label: "Mexico", phone: "52", phoneLength: 10, flag: "🇲🇽" },
  { code: "MY", label: "Malaysia", phone: "60", phoneLength: 7, flag: "🇲🇾" },
  {
    code: "MZ",
    label: "Mozambique",
    phone: "258",
    phoneLength: 12,
    flag: "🇲🇿",
  },
  { code: "NA", label: "Namibia", phone: "264", phoneLength: 7, flag: "🇳🇦" },
  {
    code: "NC",
    label: "New Caledonia",
    phone: "687",
    phoneLength: 6,
    flag: "🇳🇨",
  },
  { code: "NE", label: "Niger", phone: "227", phoneLength: 8, flag: "🇳🇪" },
  {
    code: "NF",
    label: "Norfolk Island",
    phone: "672",
    phoneLength: 6,
    flag: "🇳🇫",
  },
  { code: "NG", label: "Nigeria", phone: "234", phoneLength: 8, flag: "🇳🇬" },
  { code: "NI", label: "Nicaragua", phone: "505", phoneLength: 8, flag: "🇳🇮" },
  { code: "NL", label: "Netherlands", phone: "31", phoneLength: 9, flag: "🇳🇱" },
  { code: "NO", label: "Norway", phone: "47", phoneLength: 8, flag: "🇳🇴" },
  { code: "NP", label: "Nepal", phone: "977", phoneLength: 10, flag: "🇳🇵" },
  { code: "NR", label: "Nauru", phone: "674", phoneLength: 7, flag: "🇳🇷" },
  { code: "NU", label: "Niue", phone: "683", phoneLength: 4, flag: "🇳🇺" },
  {
    code: "NZ",
    label: "New Zealand",
    phone: "64",
    phoneLength: [8, 9],
    flag: "🇳🇿",
  },
  { code: "OM", label: "Oman", phone: "968", phoneLength: 8, flag: "🇴🇲" },
  { code: "PA", label: "Panama", phone: "507", phoneLength: 8, flag: "🇵🇦" },
  { code: "PE", label: "Peru", phone: "51", phoneLength: 9, flag: "🇵🇪" },
  {
    code: "PF",
    label: "French Polynesia",
    phone: "689",
    phoneLength: 8,
    flag: "🇵🇫",
  },
  {
    code: "PG",
    label: "Papua New Guinea",
    phone: "675",
    phoneLength: 8,
    flag: "🇵🇬",
  },
  {
    code: "PH",
    label: "Philippines",
    phone: "63",
    phoneLength: 10,
    flag: "🇵🇭",
  },
  { code: "PK", label: "Pakistan", phone: "92", phoneLength: 10, flag: "🇵🇰" },
  { code: "PL", label: "Poland", phone: "48", phoneLength: 9, flag: "🇵🇱" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
    phoneLength: 6,
    flag: "🇵🇲",
  },
  { code: "PN", label: "Pitcairn", phone: "870", phoneLength: 9, flag: "🇵🇳" },
  { code: "PR", label: "Puerto Rico", phone: "1", phoneLength: 10, flag: "🇵🇷" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "970",
    phoneLength: 9,
    flag: "🇵🇸",
  },
  { code: "PT", label: "Portugal", phone: "351", phoneLength: 9, flag: "🇵🇹" },
  { code: "PW", label: "Palau", phone: "680", phoneLength: 7, flag: "🇵🇼" },
  { code: "PY", label: "Paraguay", phone: "595", phoneLength: 9, flag: "🇵🇾" },
  { code: "QA", label: "Qatar", phone: "974", phoneLength: 8, flag: "🇶🇦" },
  { code: "RE", label: "Reunion", phone: "262", phoneLength: 10, flag: "🇷🇪" },
  { code: "RO", label: "Romania", phone: "40", phoneLength: 10, flag: "🇷🇴" },
  { code: "RS", label: "Serbia", phone: "381", phoneLength: 9, flag: "🇷🇸" },
  {
    code: "RU",
    label: "Russian Federation",
    phone: "7",
    phoneLength: 10,
    flag: "🇷🇺",
  },
  { code: "RW", label: "Rwanda", phone: "250", phoneLength: 9, flag: "🇷🇼" },
  {
    code: "SA",
    label: "Saudi Arabia",
    phone: "966",
    phoneLength: 9,
    flag: "🇸🇦",
  },
  {
    code: "SB",
    label: "Solomon Islands",
    phone: "677",
    phoneLength: 7,
    flag: "🇸🇧",
  },
  { code: "SC", label: "Seychelles", phone: "248", phoneLength: 7, flag: "🇸🇨" },
  { code: "SD", label: "Sudan", phone: "249", phoneLength: 7, flag: "🇸🇩" },
  { code: "SE", label: "Sweden", phone: "46", phoneLength: 7, flag: "🇸🇪" },
  { code: "SG", label: "Singapore", phone: "65", phoneLength: 8, flag: "🇸🇬" },
  {
    code: "SH",
    label: "Saint Helena",
    phone: "290",
    phoneLength: 4,
    flag: "🇸🇭",
  },
  { code: "SI", label: "Slovenia", phone: "386", phoneLength: 9, flag: "🇸🇮" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
    phoneLength: 8,
    flag: "🇸🇯",
  },
  { code: "SK", label: "Slovakia", phone: "421", phoneLength: 9, flag: "🇸🇰" },
  {
    code: "SL",
    label: "Sierra Leone",
    phone: "232",
    phoneLength: 8,
    flag: "🇸🇱",
  },
  {
    code: "SM",
    label: "San Marino",
    phone: "378",
    phoneLength: 10,
    flag: "🇸🇲",
  },
  { code: "SN", label: "Senegal", phone: "221", phoneLength: 9, flag: "🇸🇳" },
  {
    code: "SO",
    label: "Somalia",
    phone: "252",
    phoneLength: [8, 9],
    flag: "🇸🇴",
  },
  {
    code: "SR",
    label: "Suriname",
    phone: "597",
    phoneLength: [6, 7],
    flag: "🇸🇷",
  },
  {
    code: "SS",
    label: "South Sudan",
    phone: "211",
    phoneLength: 7,
    flag: "🇸🇸",
  },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "239",
    phoneLength: 7,
    flag: "🇸🇹",
  },
  {
    code: "SV",
    label: "El Salvador",
    phone: "503",
    phoneLength: 8,
    flag: "🇸🇻",
  },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
    phoneLength: 10,
    flag: "🇸🇽",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
    phoneLength: 7,
    flag: "🇸🇾",
  },
  { code: "SZ", label: "Swaziland", phone: "268", phoneLength: 8, flag: "🇸🇿" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
    phoneLength: 10,
    flag: "🇹🇨",
  },
  { code: "TD", label: "Chad", phone: "235", phoneLength: 6, flag: "🇹🇩" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
    phoneLength: 10,
    flag: "🇹🇫",
  },
  { code: "TG", label: "Togo", phone: "228", phoneLength: 8, flag: "🇹🇬" },
  { code: "TH", label: "Thailand", phone: "66", phoneLength: 9, flag: "🇹🇭" },
  { code: "TJ", label: "Tajikistan", phone: "992", phoneLength: 9, flag: "🇹🇯" },
  { code: "TK", label: "Tokelau", phone: "690", phoneLength: 5, flag: "🇹🇰" },
  {
    code: "TL",
    label: "Timor-Leste",
    phone: "670",
    phoneLength: 7,
    flag: "🇹🇱",
  },
  {
    code: "TM",
    label: "Turkmenistan",
    phone: "993",
    phoneLength: 8,
    flag: "🇹🇲",
  },
  { code: "TN", label: "Tunisia", phone: "216", phoneLength: 8, flag: "🇹🇳" },
  { code: "TO", label: "Tonga", phone: "676", phoneLength: 5, flag: "🇹🇴" },
  { code: "TR", label: "Turkey", phone: "90", phoneLength: 11, flag: "🇹🇷" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
    phoneLength: 7,
    flag: "🇹🇹",
  },
  { code: "TV", label: "Tuvalu", phone: "688", phoneLength: 5, flag: "🇹🇻" },
  {
    code: "TW",
    label: "Taiwan, Province of China",
    phone: "886",
    phoneLength: 9,
    flag: "🇹🇼",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
    phoneLength: 7,
    flag: "🇹🇿",
  },
  { code: "UA", label: "Ukraine", phone: "380", phoneLength: 9, flag: "🇺🇦" },
  { code: "UG", label: "Uganda", phone: "256", phoneLength: 7, flag: "🇺🇬" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
    phoneLength: 10,
    flag: "🇺🇸",
  },
  { code: "UY", label: "Uruguay", phone: "598", phoneLength: 8, flag: "🇺🇾" },
  { code: "UZ", label: "Uzbekistan", phone: "998", phoneLength: 9, flag: "🇺🇿" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
    phoneLength: 10,
    flag: "🇻🇦",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
    phoneLength: 7,
    flag: "🇻🇨",
  },
  { code: "VE", label: "Venezuela", phone: "58", phoneLength: 7, flag: "🇻🇪" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
    phoneLength: 7,
    flag: "🇻🇬",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "1-340",
    phoneLength: 10,
    flag: "🇻🇮",
  },
  { code: "VN", label: "Vietnam", phone: "84", phoneLength: 9, flag: "🇻🇳" },
  { code: "VU", label: "Vanuatu", phone: "678", phoneLength: 5, flag: "🇻🇺" },
  {
    code: "WF",
    label: "Wallis and Futuna",
    phone: "681",
    phoneLength: 6,
    flag: "🇼🇫",
  },
  {
    code: "WS",
    label: "Samoa",
    phone: "685",
    phoneLength: [5, 6, 7],
    flag: "🇼🇸",
  },
  { code: "XK", label: "Kosovo", phone: "383", phoneLength: 8, flag: "🇽🇰" },
  { code: "YE", label: "Yemen", phone: "967", phoneLength: 9, flag: "🇾🇪" },
  { code: "YT", label: "Mayotte", phone: "262", phoneLength: 9, flag: "🇾🇹" },
  {
    code: "ZA",
    label: "South Africa",
    phone: "27",
    phoneLength: 9,
    flag: "🇿🇦",
  },
  { code: "ZM", label: "Zambia", phone: "260", phoneLength: 9, flag: "🇿🇲" },
  { code: "ZW", label: "Zimbabwe", phone: "263", phoneLength: 9, flag: "🇿🇼" },
];
